### ISSUE TITLE
Application Design: Activities or Fragments

### ISSUE THREAD

**Issue by kumarsookram** [kumarsookram/comp6901project#4]
@KimiiG @jayron1 Looking at the android app design. I am thinking of using the ModelView Fragment option. The ArgiExpense utilized more Activities. Is there a preference to which model to use?

**Comment by KimiiG** [comment]
I personally do not have a preference on which model to use.

**Comment by jayron1** [comment]
I think the viewModel is a better option than continuously recalling the same methods through the activity when a change occurs. Once the view model exist the first request will stay until the activity is completed and removed. However even though viewModel is a better option I do not mind using the Activities model if you all think its easier...
